<?php

return [
    ['id' => 1, 'user_id' => 3, 'address_id' => 4, 'payment_type_id' => 1, 'status' => 1, 'delivery_method_id' => 2, 'delivery_address_id' => 4],
    ['id' => 2, 'user_id' => 7, 'address_id' => 8, 'payment_type_id' => 2, 'status' => 0, 'delivery_method_id' => 1, 'delivery_address_id' => 8],
    ['id' => 3, 'user_id' => 5, 'address_id' => 6, 'payment_type_id' => 2, 'status' => 1, 'delivery_method_id' => 3, 'delivery_address_id' => 6],
    ['id' => 4, 'user_id' => 2, 'address_id' => 2, 'payment_type_id' => 2, 'status' => 0, 'delivery_method_id' => 1, 'delivery_address_id' => 2],
    ['id' => 5, 'user_id' => 8, 'address_id' => 9, 'payment_type_id' => 2, 'status' => 1, 'delivery_method_id' => 2, 'delivery_address_id' => 9],
    ['id' => 6, 'user_id' => 1, 'address_id' => 1, 'payment_type_id' => 1, 'status' => 1, 'delivery_method_id' => 3, 'delivery_address_id' => 1],
    ['id' => 7, 'user_id' => 6, 'address_id' => 7, 'payment_type_id' => 1, 'status' => 0, 'delivery_method_id' => 1, 'delivery_address_id' => 7],
    ['id' => 8, 'user_id' => 9, 'address_id' => 10, 'payment_type_id' => 3, 'status' => 1, 'delivery_method_id' => 2, 'delivery_address_id' => 10],
    ['id' => 9, 'user_id' => 4, 'address_id' => 5, 'payment_type_id' => 1, 'status' => 0, 'delivery_method_id' => 3, 'delivery_address_id' => 5],
    ['id' => 10, 'user_id' => 10, 'address_id' => 11, 'payment_type_id' => 1, 'status' => 1, 'delivery_method_id' => 1, 'delivery_address_id' => 11],
    ['id' => 11, 'user_id' => 3, 'address_id' => 4, 'payment_type_id' => 3, 'status' => 0, 'delivery_method_id' => 2, 'delivery_address_id' => 4],
    ['id' => 12, 'user_id' => 7, 'address_id' => 8, 'payment_type_id' => 3, 'status' => 1, 'delivery_method_id' => 3, 'delivery_address_id' => 8],
    ['id' => 13, 'user_id' => 5, 'address_id' => 6, 'payment_type_id' => 2, 'status' => 0, 'delivery_method_id' => 1, 'delivery_address_id' => 6],
    ['id' => 14, 'user_id' => 2, 'address_id' => 3, 'payment_type_id' => 3, 'status' => 1, 'delivery_method_id' => 2, 'delivery_address_id' => 3],
    ['id' => 15, 'user_id' => 8, 'address_id' => 9, 'payment_type_id' => 1, 'status' => 0, 'delivery_method_id' => 3, 'delivery_address_id' => 9],
    ['id' => 16, 'user_id' => 1, 'address_id' => 1, 'payment_type_id' => 1, 'status' => 1, 'delivery_method_id' => 1, 'delivery_address_id' => 1],
    ['id' => 17, 'user_id' => 6, 'address_id' => 7, 'payment_type_id' => 2, 'status' => 1, 'delivery_method_id' => 2, 'delivery_address_id' => 7],
    ['id' => 18, 'user_id' => 9, 'address_id' => 10, 'payment_type_id' => 1, 'status' => 0, 'delivery_method_id' => 3, 'delivery_address_id' => 10],
    ['id' => 19, 'user_id' => 4, 'address_id' => 5, 'payment_type_id' => 2, 'status' => 1, 'delivery_method_id' => 1, 'delivery_address_id' => 5],
    ['id' => 20, 'user_id' => 10, 'address_id' => 11, 'payment_type_id' => 1, 'status' => 0, 'delivery_method_id' => 2, 'delivery_address_id' => 11],
    ['id' => 21, 'user_id' => 3, 'address_id' => 4, 'payment_type_id' => 1, 'status' => 1, 'delivery_method_id' => 3, 'delivery_address_id' => 4],
    ['id' => 22, 'user_id' => 7, 'address_id' => 8, 'payment_type_id' => 3, 'status' => 0, 'delivery_method_id' => 1, 'delivery_address_id' => 8],
    ['id' => 23, 'user_id' => 5, 'address_id' => 6, 'payment_type_id' => 2, 'status' => 1, 'delivery_method_id' => 2, 'delivery_address_id' => 6],
    ['id' => 24, 'user_id' => 2, 'address_id' => 2, 'payment_type_id' => 2, 'status' => 0, 'delivery_method_id' => 3, 'delivery_address_id' => 3],
    ['id' => 25, 'user_id' => 8, 'address_id' => 9, 'payment_type_id' => 2, 'status' => 1, 'delivery_method_id' => 1, 'delivery_address_id' => 9],
    ['id' => 26, 'user_id' => 1, 'address_id' => 1, 'payment_type_id' => 3, 'status' => 1, 'delivery_method_id' => 2, 'delivery_address_id' => 1],
    ['id' => 27, 'user_id' => 6, 'address_id' => 7, 'payment_type_id' => 1, 'status' => 0, 'delivery_method_id' => 3, 'delivery_address_id' => 7],
    ['id' => 28, 'user_id' => 9, 'address_id' => 10, 'payment_type_id' => 1, 'status' => 1, 'delivery_method_id' => 1, 'delivery_address_id' => 10],
    ['id' => 29, 'user_id' => 4, 'address_id' => 5, 'payment_type_id' => 3, 'status' => 0, 'delivery_method_id' => 2, 'delivery_address_id' => 5],
    ['id' => 30, 'user_id' => 10, 'address_id' => 11, 'payment_type_id' => 1, 'status' => 1, 'delivery_method_id' => 3, 'delivery_address_id' => 11],
];
