services:
  app:
    build: .
    container_name: sor-tokajuk-sklep.app
    restart: unless-stopped
    ports:
      - 8002:80
    volumes:
      - ./:/var/www/html

  database:
    container_name: sor-tokajuk-sklep.database
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
      - 8003:3306
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: true